.PHONY: clean All

All:
	@echo "----------Building project:[ peripheral_unit1 - Debug ]----------"
	@cd "door" && "$(MAKE)" -f  "peripheral_unit1.mk" && "$(MAKE)" -f  "peripheral_unit1.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ peripheral_unit1 - Debug ]----------"
	@cd "door" && "$(MAKE)" -f  "peripheral_unit1.mk" clean
